config/routes.rb
Rss::Application.routes.draw do
  resources :feeds
  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root :to => 'sessions#new'

  match '/signup',  to: 'users#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match 'add-feed/:feed.json' => 'feeds#create'

  

end

app/models/feed.rb
class Feed < ActiveRecord::Base
  attr_accessible :url
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  has_and_belongs_to_many :feeds

  before_save {|user| user.email = email.downcase}
  validates :name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, 
  									format: { with: VALID_EMAIL_REGEX }, 
  									uniqueness: {case_sensitive: false} 
  validates :password, presence: true, length: {minimum: 8}
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def user_logged_in?
  	return !session[:email].nil?
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feeds }
    end
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
    @feed = Feed.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/new
  # GET /feeds/new.json
  def new
    @feed = Feed.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feed }
    end
  end

  # GET /feeds/1/edit
  def edit
    @feed = Feed.find(params[:id])
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.find_by_url(params[:feed])
    if @feed.nil?
      @feed = Feed.new(:url => params[:feed])
    end

    # TODO find user from session[:email], associate feed with user and save all that shit.


    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render json: @feed, status: :created, location: @feed }
      else
        format.html { render action: "new" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feeds/1
  # PUT /feeds/1.json
  def update
    @feed = Feed.find(params[:id])

    respond_to do |format|
      if @feed.update_attributes(params[:feed])
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed = Feed.find(params[:id])
    @feed.destroy

    respond_to do |format|
      format.html { redirect_to feeds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		if !session[:email].nil?
			@user = User.find_by_email(session[:email].downcase)
			respond_to do |format|
		    format.html {redirect_to @user, notice: 'User logged in.'}
	      format.json { render json: @user, status: :created, location: @user }
	    end
		end

	end

	def create
		@user = User.find_by_email(params[:session][:email].downcase)
	  if @user && @user.authenticate(params[:session][:password])
	    session[:name] = @user.name
	    session[:email] = @user.email

		  respond_to do |format|
		    format.html {redirect_to @user, notice: 'User was successfully logged in.'}
	      format.json { render json: @user, status: :created, location: @user }
	    end
		else  	
		    # Create an error message and re-render the signin form.
	  end
	end

	def destroy

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if user_logged_in?
      @user = User.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @user }
      end
    else
      respond_to do |format|
        format.html {redirect_to '/', notice: "Please log in"}
        format.json { render json: @user }
      end
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<h1>Listing feeds</h1>

<table>
  <tr>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.url %></td>
    <td><%= link_to 'Show', feed %></td>
    <td><%= link_to 'Edit', edit_feed_path(feed) %></td>
    <td><%= link_to 'Destroy', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @feed.url %>
</p>


<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rss</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_sign_up_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.text_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit 'Create account' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Pass</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.pass %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Top Secret:</h1>

<%= render 'sign_up_form' %>

app/views/users/show.html.erb
<div id="content">
	<div id="header">
		<h3>Stuff</h3>
	</div>
	<div class="main-content">
		
		<div class="left-col">
			<span>This is some shiz in the left col</span>
		</div>
		<div class="right-col">
			<input type="text" id="add-feed-url-text" placeholder="Feed url"/>
			<input type="button" id="add-feed-url-button" value="Add" />
		</div>
	</div>
</div>